---
- hosts: all
  become: yes
  tasks:
  - name: create ansible nodes
    ec2:
      key_name: virginia
      group: ansible
      instance_type: t2.micro
      image: ami-0ce06bf2f8dd30cd5
      wait: yes
      region: us-east-1
      wait_timeout: 500
      count: 2
      instance_tags:
         name: ansiblenodes
      vpc_subnet_id: subnet-3ab35065
      assign_public_ip: yes

